#!/usr/bin/env python3
"""
Extract schema/routines/triggers from a phpMyAdmin-style SQL dump by removing
top-level data INSERT/REPLACE statements while preserving DELIMITER blocks.

Usage:
  python tools/db/extract_schema_from_dump.py <input_dump.sql> <output_schema.sql>
"""

from __future__ import annotations

import re
import sys


def main(argv: list[str]) -> int:
    if len(argv) != 3 or argv[1] in {"-h", "--help"}:
        print(__doc__.strip())
        return 2 if len(argv) != 3 else 0

    in_path = argv[1]
    out_path = argv[2]

    # Track current delimiter so we don't accidentally strip INSERTs inside
    # triggers/routines (which usually set a custom delimiter like $$).
    delimiter = ";"

    # When skipping a top-level INSERT/REPLACE statement, we skip whole lines
    # until we see the statement terminator. For dumps generated by phpMyAdmin,
    # the terminator is expected at the end of a line.
    skipping_data_stmt = False

    re_delim = re.compile(r"^\s*DELIMITER\s+(\S+)\s*$", re.IGNORECASE)

    with open(in_path, "r", encoding="utf-8", errors="replace", newline="") as fin, open(
        out_path, "w", encoding="utf-8", newline=""
    ) as fout:
        fout.write(f"-- Extracted schema only from: {in_path}\n")
        fout.write("-- NOTE: Data INSERT/REPLACE statements were removed.\n\n")

        for line in fin:
            m = re_delim.match(line)
            if m and not skipping_data_stmt:
                delimiter = m.group(1)
                fout.write(line)
                continue

            if skipping_data_stmt:
                # Only skip when we're in the normal ';' delimiter mode.
                # For custom delimiters, we shouldn't be in skipping mode.
                if delimiter == ";" and line.rstrip().endswith(";"):
                    skipping_data_stmt = False
                continue

            stripped = line.lstrip()
            upper = stripped.upper()

            # Reduce file size: drop data-section headers.
            if stripped.startswith("-- Dumping data for table"):
                continue

            # Remove top-level data statements (but keep INSERTs inside DELIMITER blocks).
            if delimiter == ";" and (upper.startswith("INSERT INTO ") or upper.startswith("REPLACE INTO ")):
                skipping_data_stmt = True
                if line.rstrip().endswith(";"):
                    skipping_data_stmt = False
                continue

            fout.write(line)

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))

